version: '3'

services:
  db:
    image: mysql/mysql-server:8.0
    container_name: mysql-8-0
    restart: always
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - app
    volumes:
      - my-db:/var/lib/mysql
networks:
  app:
    driver: bridge
volumes:
  my-db: