package com.example.lr20190024.users.enums;

public enum PrivilegeName {
    CREATE_USER,
    VIEW_USER,
    STORE_USER,
    UPDATE_USER,
    DELETE_USER,

    CREATE_CLIENT,
    VIEW_CLIENT,
    STORE_CLIENT,
    UPDATE_CLIENT,
    DELETE_CLIENT,

    CREATE_PIPELINE,
    VIEW_PIPELINE,
    STORE_PIPELINE,
    UPDATE_PIPELINE,
    DELETE_PIPELINE,

    CREATE_STAGE,
    VIEW_STAGE,
    STORE_STAGE,
    UPDATE_STAGE,
    DELETE_STAGE,

    CREATE_DEAL,
    VIEW_DEAL,
    STORE_DEAL,
    UPDATE_DEAL,
    DELETE_DEAL,

    CREATE_ACTIVITY,
    VIEW_ACTIVITY,
    STORE_ACTIVITY,
    UPDATE_ACTIVITY,
    DELETE_ACTIVITY,

    CREATE_NOTE,
    VIEW_NOTE,
    STORE_NOTE,
    UPDATE_NOTE,
    DELETE_NOTE,
}
